//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanCongGiangDay.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DmBoMon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DmBoMon()
        {
            this.DmHocPhans = new HashSet<DmHocPhan>();
        }
    
        public int Id { get; set; }
        public string MaBoMon { get; set; }
        public string TenBoMon { get; set; }
        public string ThongTinBoMon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DmHocPhan> DmHocPhans { get; set; }
    }
}
