//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanCongGiangDay.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoiLuongPhanCong
    {
        public int Id { get; set; }
        public int GiangVienId { get; set; }
        public Nullable<double> KhoiLuong { get; set; }
        public Nullable<double> KhoiLuongDoAn { get; set; }
        public Nullable<int> SoLuongLop { get; set; }
        public Nullable<int> SoLuongSVDA { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
    }
}
