//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanCongGiangDay.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LopHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopHoc()
        {
            this.ThoiGianLopHocs = new HashSet<ThoiGianLopHoc>();
        }
    
        public int Id { get; set; }
        public string MaLop { get; set; }
        public string MaHocPhan { get; set; }
        public Nullable<int> SoSinhVien { get; set; }
        public int ChuongTrinhId { get; set; }
        public Nullable<double> KhoiLuongLop { get; set; }
        public string LoaiLop { get; set; }
        public int TrangThaiPhanCong { get; set; }
        public string HocKy { get; set; }
    
        public virtual DmChuongTrinh DmChuongTrinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThoiGianLopHoc> ThoiGianLopHocs { get; set; }
    }
}
