//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanCongGiangDay.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhatKyHeTHong
    {
        public int Id { get; set; }
        public int NguoiDungId { get; set; }
        public string MoTa { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual QLNguoiDung QLNguoiDung { get; set; }
    }
}
