//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanCongGiangDay.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThoiGianLopHoc
    {
        public int Id { get; set; }
        public int LopHocId { get; set; }
        public string Tuan { get; set; }
        public Nullable<int> Thu { get; set; }
        public Nullable<int> TietBatDau { get; set; }
        public Nullable<int> TietKetThuc { get; set; }
        public string DiaDiem { get; set; }
    
        public virtual LopHoc LopHoc { get; set; }
    }
}
