//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanCongGiangDay.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaiTroQuyen
    {
        public int Id { get; set; }
        public int VaiTroId { get; set; }
        public int QuyenId { get; set; }
    
        public virtual Quyen Quyen { get; set; }
        public virtual VaiTro VaiTro { get; set; }
    }
}
